# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(329, 550)
        MainWindow.setStyleSheet("background-color: #ffffff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: white")
        self.centralwidget.setObjectName("centralwidget")
        self.input_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.input_currency.setGeometry(QtCore.QRect(30, 150, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.input_currency.setFont(font)
        self.input_currency.setStyleSheet("background-color: white;\n"
"border: 3px solid rgb(85, 85, 0);\n"
"border-radius: 30px;\n"
"color: black")
        self.input_currency.setText("")
        self.input_currency.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_currency.setObjectName("input_currency")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 470, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-color: rgb(170, 170, 127);\n"
"border-radius: 30px;\n"
"}\n"
"QPushButton: pressed {\n"
"background-color: rgb(120, 120, 89);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, 0, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label.setStyleSheet("background-color: rgb(170, 170, 127);\n"
"color: white;")
        self.label.setLineWidth(-1)
        self.label.setMidLineWidth(0)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(30, 230, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.input_amount.setFont(font)
        self.input_amount.setStyleSheet("background-color: white;\n"
"border: 3px solid rgb(85, 85, 0);\n"
"border-radius: 30px;\n"
"color: black")
        self.input_amount.setText("")
        self.input_amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        self.output_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.output_amount.setGeometry(QtCore.QRect(30, 390, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.output_amount.setFont(font)
        self.output_amount.setStyleSheet("background-color: white;\n"
"border: 3px solid rgb(85, 85, 0);\n"
"border-radius: 30px;\n"
"color: black")
        self.output_amount.setText("")
        self.output_amount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_amount.setObjectName("output_amount")
        self.output_currency = QtWidgets.QLineEdit(self.centralwidget)
        self.output_currency.setGeometry(QtCore.QRect(30, 310, 271, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.output_currency.setFont(font)
        self.output_currency.setStyleSheet("background-color: white;\n"
"border: 3px solid rgb(85, 85, 0);\n"
"border-radius: 30px;\n"
"color: black")
        self.output_currency.setText("")
        self.output_currency.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.output_currency.setObjectName("output_currency")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "CONVERT!"))
        self.label.setText(_translate("MainWindow", "CURRENCY CONVERTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
